export const DEFAULT_STRESS_OVERRIDES = {
  character: 0,
  criticism: 0,
  increase: { noun: 0 },
  legendary: 0,
  mechanism: 0,
  narrative: 0,
  quality: 0,
  symbol: 0,
  image: 0,
  popular: 0,
  optimism: 0,
  document: { noun: 0 },
  paragraph: 0,
  summary: 0,
  focus: 0,
  government: 0,
  summarise: { verb: 0 },
  emphasize: { verb: 0 },
  emphasise: { verb: 0 },
  probably: 0,
  necessary: 0,

  evolve: { verb: 1 },
  beginning: 1,
  considered: 1,
  determine: { verb: 1 },
  however: 1,
  materialism: 1,
  respect: { verb: 1 },
  whereas: 1,
  absurd: 1,
  antagonism: 1,
  imperialism: 1,
  colonialism: 1,
  conservatism: 1,
  analysis: 1,

  representative: 2,
  correspondence: 2,
  european: 2,
  introduce: { verb: 2 },
  paradoxical: 2,
  colonisation: 2,
  colonization: 2,
  civilisation: 2,
  civilization: 2,
  imagination: 2,
  introduction: 2,
  conclusion: 2,
  comparison: 2,
  description: 2,
  represent: { verb: 2 },
  disagree: 2
};
