export const STRIPE_PRICES = {
  O_COACHING_SINGLE: process.env.STRIPE_PRICE_O_COACHING_SINGLE,

  SO_COACHING_PILOT: process.env.STRIPE_PRICE_O_COACHING_PILOT,

  O_COACHING_MONTHLY: process.env.STRIPE_PRICE_O_COACHING_MONTHLY,

  I_P_COACHING_SINGLE: process.env.STRIPE_PRICE_I_P_COACHING_SINGLE,

  I_P_COACHING_PILOT: process.env.STRIPE_PRICES_I_P_COACHING_PILOT,

  I_P_COACHING_MONTHLY: process.env.STRIPE_PRICE_I_P_COACHING_MONTHLY,
  O_WORKSHOP_SINGLE: process.env.STRIPE_PRICE_O_WORKSHOP_SINGLE,

  O_WORKSHOP_PILOT: process.env.STRIPE_PRICE_O_WORKSHOP_PILOT,
  O_WORKSHOP_MONTHLY: process.env.STRIPE_PRICE_O_WORKSHOP_MONTHLY,
  O_S_WORKSHOP_SINGLE: process.env.STRIPE_PRICE_O_S_WORKSHOP_SINGLE,

  O_S_WORKSHOP_PILOT: process.env.STRIPE_PRICE_O_S_WORKSHOP_PILOT,
  O_S_WORKSHOP_MONTHLY: process.env.STRIPE_PRICE_O_S_WORKSHOP_MONTHLY,
}
